@startuml 02-05_ACT_ちょい気に登録
    title 02-05 ちょい気に登録

    start
    partition ルーティング {
        
        :POSTリクエストの受信;
        :リクエストヘッダからトークンの取得;
        :パラメータ整理・変数保持;

        :取得処理|
        partition 取得処理 {
            
            :ユーザ名とトークンに対応するドキュメントを取得;
            if (取得処理例外発生? \n or 該当データなし?) then (yes)
                :処理エラー「ユーザ情報取得失敗」;
                stop
                
            endif

            :ユーザの_idに紐づくちょい気にリストをUPSERT;
            if (取得処理例外発生?) then (yes)
                :処理エラー「ちょい気に取得失敗」;
                stop
                
            endif

        }

        if (例外ない?) then (yes)
            :登録成功の\nHAL生成;
        else (no)
            :登録失敗の\nHAL生成;
        endif
        
    }

    end
    

@enduml