@startuml 02-06_ACT_ちょい気に取得
    title 全ちょい気に取得

    start
    partition ルーティング {
        
        :GETリクエストの受信;
        :リクエストヘッダからトークンの取得;
        :パラメータ整理・変数保持;

        :取得処理|
        partition 取得処理 {
            
            :ユーザ名とトークンに対応するドキュメントを取得;
            if (取得処理例外発生? \n or 該当データなし?) then (yes)
                :処理エラー「ユーザ情報取得失敗」;
                stop
                
            endif

            if (ログインユーザの権限は不足している?) then (yes)
                :処理エラー「ユーザ権限不正」;
                stop
            endif

            :全ユーザのちょい気にを取得;
            if (取得処理例外発生?) then (yes)
                :処理エラー「ちょい気に取得失敗」;
                stop
                
            endif

            :全ユーザのちょい気にのリストをオブジェクトに格納;
        }

        if (例外ない?) then (yes)
            :オブジェクトから\nHAL生成;
        else (no)
            :Errorオブジェクトから\nHAL生成;
        endif
        
    }
    end
@enduml