@startuml 02-02_ACT_ログイン処理
title 02-02 ログイン処理
    start
    
    partition ルーティング {

        :POSTリクエストの受信;
        :パラメータの整理・変数保持;
        
        :ログイン処理|
        partition ログイン処理 {
            
            :DAO-ログイン処理|
            partition DAO-ログイン処理 {
                
                :ユーザ名に対応するドキュメントを取得;
                if (取得処理例外発生? \n or 該当データなし?) then (yes)
                    :処理エラー「ユーザ情報取得失敗」;
                    stop
                    
                endif

                :受け取ったパスワードとドキュメントから取得したSaltを元に暗号化→暗号化.パスワード;
                :暗号化したパスワードとドキュメントのパスワードを突合;

                if (暗号化後パスワード一致する？) then (yes)
                    :現在日時を取得;
                    :「現在日時 + ユーザ名」をドキュメント.Saltで暗号化→トークン;

                    :各値をUserオブジェクトに格納;

                else (no)
                    :DBエラー「認証失敗」;
                    stop
                    
                endif
            }


            if (例外ない?) then (yes)
                :Userオブジェクトから\nHAL生成;
            else (no)
                :Errorオブジェクトから\nHAL生成;
            endif
            
        }

        :HALに情報追加(_links);
        :レスポンス;
        
    }

    end

@enduml